version: '3'
services:
  web:
    image: webdevops/php-apache
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    environment:
      WEB_DOCUMENT_ROOT: /var/www/web
  db:
    image: mysql
    command: [ "mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ap2
      MYSQL_PASSWORD: ap2
      MYSQL_DATABASE: ap2